---
# url: "https://petstore.swagger.io/v2/swagger.json"
url: "http://localhost:3200/bb2_fhir.json"
dom_id: "#swagger-ui"
validatorUrl: "https://online.swagger.io/validator"
# oauth2RedirectUrl: "http://localhost/oauth2-redirect.html"
oauth2RedirectUrl: "/oauth2-redirect.html"
# oauth2RedirectUrl: "http://localhost:3200/oauth2-redirect.html"
